name: Build Windows

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download WindowsSDK
        run: |
          curl -L -o WindowsSDK.zip https://github.com/GoldenCheetah/WindowsSDK/releases/latest/download/WindowsSDK.zip
          Expand-Archive WindowsSDK.zip -DestinationPath C:\WindowsSDK

      - name: Setup Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.7.*'
          arch: win64_msvc2019_64

      - name: Build
        run: |
          copy src\gcconfig.pri.in src\gcconfig.pri
          qmake GoldenCheetah.pro
          nmake release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GoldenCheetah-Windows
          path: src/release/*.exe
